### ISSUE TITLE
Share page

### ISSUE THREAD

**Issue by red-led** [RandoApp/rando4.me#2]
Where is code for pages like 'https://rando4.me/s/63bcba054151391eb02c9e53bc3a582f0621ccc9d2' ?

There are double twitter link in footer and some https issues

**Comment by red-led** [comment]
@xp-vit ?

**Comment by xp-vit** [comment]
@red-led The page template is located in another repository:
https://github.com/RandoApp/Rando/blob/master/template/share.template.html

This is not really obvious, but we have plan to reorganize our code in future :-)

Thanks for contacting.

**Comment by xp-vit** [comment]
https://github.com/RandoApp/Rando/pull/73 fixed double Twitter button. Closing the issue.

@red-led  Thanks!
